// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR234PqQEg8dK0zS1K-Yn3wP2nxumqo10',
    appId: '1:300047113775:web:605a3cbe270db5c629b0da',
    messagingSenderId: '300047113775',
    projectId: 'learning-datac-app',
    authDomain: 'learning-datac-app.firebaseapp.com',
    storageBucket: 'learning-datac-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf8w--LDPXqcWq1gTNfNRusmrfgdpqST4',
    appId: '1:300047113775:android:cd68d6c9d7ee804a29b0da',
    messagingSenderId: '300047113775',
    projectId: 'learning-datac-app',
    storageBucket: 'learning-datac-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTfmsN0ELvZP5Ps8prPT2isY8yPmXjPfo',
    appId: '1:300047113775:ios:6b5b0594a3a0bccb29b0da',
    messagingSenderId: '300047113775',
    projectId: 'learning-datac-app',
    storageBucket: 'learning-datac-app.firebasestorage.app',
    iosBundleId: 'com.example.training',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTfmsN0ELvZP5Ps8prPT2isY8yPmXjPfo',
    appId: '1:300047113775:ios:6b5b0594a3a0bccb29b0da',
    messagingSenderId: '300047113775',
    projectId: 'learning-datac-app',
    storageBucket: 'learning-datac-app.firebasestorage.app',
    iosBundleId: 'com.example.training',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR234PqQEg8dK0zS1K-Yn3wP2nxumqo10',
    appId: '1:300047113775:web:8ee7fd40298da65229b0da',
    messagingSenderId: '300047113775',
    projectId: 'learning-datac-app',
    authDomain: 'learning-datac-app.firebaseapp.com',
    storageBucket: 'learning-datac-app.firebasestorage.app',
  );
}
